### ISSUE TITLE
unnecessary files and branches

### ISSUE THREAD

**Issue by maureeungaro** [charlymr/XlsxReaderWriter#14]
The international standard PDF file c061750_ISO_IEC_29500-1_2012.pdf is not really needed in this repo is it? I would link it in the README instead. 

The file XlsxReaderWriter.framework.zip is also not needed - should be a tagged release.

The branches up to 2.4.0.Beta.4 are not really needed. I suggest to use the GitHub tag mechanism to produce releases.

**Comment by charlymr** [comment]
Yep will clé an ou the repo
