### ISSUE TITLE
Module 'SSZipArchive' not found on build

### ISSUE THREAD

**Issue by carsonreid** [charlymr/XlsxReaderWriter#21]
I am trying to use this library in an OSX project (10.13) and I am getting 'Module 'SSZipArchive' not found' after following the instructions - I also get the error when I try to build the demo projects included.

**Comment by charlymr** [comment]
Hello, I will look into that. It's seems to be as problem with the new Xcode and Cocoapods

**Comment by carsonreid** [comment]
Thank you, for reference I am running Xcode 10.1 (10B61)

**Comment by charlymr** [comment]
I updated for Xcode 11 but it should work on 10. Can you try on develop branch and let me know
