### ISSUE TITLE
Minimum iOS version

### ISSUE THREAD

**Issue by ddaddy** [charlymr/XlsxReaderWriter#25]
In your last commits, did you mean to bump the minimum iOS version to 12?

I'd already bumped it to 9.0 as that's the lowest Xcode 12 will allow, but it's now set at 12.0 which means when building with Carthage it is not building the armv7 slice.

Can I/you change it back to 9.0 minimum?

**Comment by charlymr** [comment]
Hello

No I did not. (If you have a working update, please create a PR)

Otherwise, since Xcode12.2 is out now, I will try and update that (maybe this week-end) so we build all slice. 

Thanks

Denis

**Comment by ddaddy** [comment]
I've submitted a pull request.
