### ISSUE TITLE
Error saving Copy of Excel File

### ISSUE THREAD

**Issue by willm132** [charlymr/XlsxReaderWriter#29]
I have an excel file embedded in my project. A function is ran that will open the file, save the date to cell J9, then save the file as.

This is all working properly, but when opening the file I am getting this error:

"We found a problem with some content in 'Test.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes."

        if let documentPath = Bundle.main.path(forResource: "Test1", ofType: "xlsx") {
            let spreadsheet: BRAOfficeDocumentPackage = BRAOfficeDocumentPackage.open(documentPath)
            let worksheet: BRAWorksheet = spreadsheet.workbook.worksheets[0] as! BRAWorksheet
            
            worksheet.cell(forCellReference: "J9", shouldCreate: true).setStringValue("\(currentDate)")
            
            let documentDirectory = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor:nil, create:false)
            let fileURL = documentDirectory.appendingPathComponent("TestResult.xlsx")
            let formatURLForIOS = "\(fileURL.absoluteString.dropFirst(6))"
            spreadsheet.save(as: formatURLForIOS)
        } else {
            print("file not found")
            self.errorUnableToCreateBOL()
        }

I will note that the original file opens without any issues it's just the new one that is generated that is not opening properly.

**Comment by willm132** [comment]
This was actually caused by the URL used to save.

**Comment by charlymr** [comment]
@willm132 all good then :) Thanks.
