### ISSUE TITLE
Excluded architecture arm64

### ISSUE THREAD

**Issue by ddaddy** [charlymr/XlsxReaderWriter#30]
I was just wondering if there was a valid reason for excluding the `arm64` architecture from MacOS?
```
EXCLUDED_ARCHS = arm64;
```

Is it just that you don't have an M1 Mac and need to exclude it?
I just got an M1 and had to enable it and it seems to build fine.

**Comment by charlymr** [comment]
Hello,
yes I don't have an M1 Mac and was causing issue for me. If you could actually push in a PR the build that include the slice, it would be great.
Thanks in advance,
Denis

**Comment by charlymr** [comment]
By the way, instead of Carthage, I included SPM, which I think is much easier that Cocoapods or Carthage and build regardless of the architecture. I personally moved all my project to that. :)

**Comment by ddaddy** [comment]
Yes i'll have a go at that. Is it the `/Carthage/Build/` that you want built with the M1 slice?

Although i've started using SPM for some things, I do still prefer Carthage.
It only builds once and you can trash DerivedData without it having to build again.

Plus if you ever trash DerivedData without an internet connection, you can't rebuild your SPM packages.

**Comment by charlymr** [comment]
Yes, if you can do the Archive that include all Slices, would be perfect. You'll end up with the `XlsxReaderWriter.framework.zip`, this is what I am looking for. This way, I can retag and the all slice should be included (give the M1 is capable of build X86 slices)

**Comment by ddaddy** [comment]
I've sent a pull request, however i'm not sure why it says there is a merge conflict?

**Comment by ddaddy** [comment]
Oh hang on, let me do it again. My branch wasn't up to date with yours.

**Comment by ddaddy** [comment]
Ok done. Carthage folder now has `xcframework`'s and built with `arm64` for Mac.

**Comment by charlymr** [comment]
Actually realising now I was doing it wrong! I can build any architecture, just a configuration problem in the project itself :( 

The all `xcframework`was what help me discover my mistake. So thanks for the Help. I'll release the new version shortly.

**Comment by charlymr** [comment]
And with that, I even brought back tvOS... (No sure who would work with XLSX file on the Apple TV)... But you Neve know :)

**Comment by ddaddy** [comment]
Early on, Carthage needed a few workarounds to get anything to build correctly for arm, but with the latest carthage build it works great as long as you specify `--use-xcframeworks` when you build

**Comment by charlymr** [comment]
YEs I saw that. However, you can't archive it yet :) SO looking for a work around. Will get there

**Comment by charlymr** [comment]
Done. Please test and let me know :)

**Comment by ddaddy** [comment]
You don't actually have to commit the Carthage folder in the release.
Carthage just builds it once added to a project.

**Comment by charlymr** [comment]
Yes I realised that. But if you download the Zip instead, you have the XCFramework out of the box. I should proably put that in the release tags.
