### ISSUE TITLE
working example

### ISSUE THREAD

**Issue by Nathan187** [charlymr/XlsxReaderWriter#5]
has anyone got this to work?  following the instructions in the readme..project doesn't compile . 'XMLDictionary' not found

**Comment by charlymr** [comment]
It is working for me and I am using the library in several project.
In the version 2.4.0. I removed the XMLDictionary dependency, try it:

```Ruby
## ***** IMPORTANT ***** -> Add this to your PodFile (at the top, because the main cocoapods repo is not updated for this project anymore)
source 'https://github.com/charlymr/XlsxReaderWriter-Podspecs.git' 

## Then you can get the latest version 2.4 +
    pod 'XlsxReaderWriter', '~> 2.4.0-beta'
```

Then if you clone the repo, you can find working examples in the Tests...

**Comment by Nathan187** [comment]
thanks for answering...do you see carthage support in the future?

**Comment by charlymr** [comment]
Yes the branch develop has it

**Comment by Nathan187** [comment]
Ok, just tried it and it failed.   In the log, it said that the Archive failed.   :(

**Comment by charlymr** [comment]
I release a version 2 for the 2.4 Beta as I found some problems. Please check it out
https://github.com/charlymr/XlsxReaderWriter/releases/tag/2.4.0-beta.2

**Comment by avubotla** [comment]
I tried so many times but not fixed following error. Please guide me how to use correctly.

BRAOfficeDocumentPackage.h' file not found

**Comment by charlymr** [comment]
I updated the Demo Cartfile and tested it. Normally it should work properly now:
https://github.com/charlymr/XlsxReaderWriter/tree/2.4.0.Beta.3
