### ISSUE TITLE
xlsx file not open in ms Excel app 

### ISSUE THREAD

**Issue by Alexander-Foster** [charlymr/XlsxReaderWriter#7]
Google SpreadSheet open 
but MS Excel not open

**Comment by Rynsuklan** [comment]
Open an Excel for Mac and saving without changes won't work too.

**Comment by charlymr** [comment]
@kor45cw @Rynsuklan I'll look into it. 
If you could provide an example of an xlsx file you are trying open, BEFORE (using the lib) and AFTER (when it won't open in Excel) it would be useful.

Thanks

**Comment by Rynsuklan** [comment]
Thanks for looking into it. I’ve attached the two files.

Many thanks
Michael

**Comment by charlymr** [comment]
[Files.zip](https://github.com/charlymr/XlsxReaderWriter/files/1860413/Files.zip)
this is what I discover so fare.

The difference between before opening and after opening seems to be in the line termination:
**Carriage Return and Line Feed (Windows)**
CRLF
\r\n
ASCII code 13 and then ASCII code 10

So I am trying to figure out why it is not doing it properly. 

After searching, it seems to look like the offender might be this line
`    return [retVal stringByAppendingString:@"\n"];
`
in https://github.com/charlymr/XlsxReaderWriter/blob/2.4.0.Beta.2/XlsxReaderWriter/NSDictionary%2BOpenXmlString.m

I will look more closely as so far I didn't succeded. Normally changing to "\r\n" should be enough, but doesn't seems to work.

Will keep checking and get back to you

**Comment by charlymr** [comment]
@Rynsuklan @kor45cw Hi There, sorry it took me a while to go back to that! But I finally found out what was the problem. I will release a Beta 3 soon

**Comment by kuglemic** [comment]
Hi @charlymr,

thanks for your great work!

Unfortunately for me this issue still exists. I attached my 2 files.

This is the code to create these files:
```
        let fileManager = FileManager.default
        let directoryURL = fileManager.urls(for: .documentDirectory, in: .userDomainMask)[0]
        let templateURL: URL = Bundle.main.url(forResource: "FileShippedInBundle", withExtension: "xlsx")!
        let spreadsheet: BRAOfficeDocumentPackage = BRAOfficeDocumentPackage.open(templateURL.path)
        let worksheet: BRAWorksheet = spreadsheet.workbook.worksheets[0] as! BRAWorksheet
        let exportURL = directoryURL.appendingPathComponent("FileAfterSavingToDocuments.xlsx")
        spreadsheet.save(as: exportURL.path)
```

Thanks for your help in advance!

[FileAfterSavingToDocuments.xlsx](https://github.com/charlymr/XlsxReaderWriter/files/2083989/FileAfterSavingToDocuments.xlsx)
[FileShippedInBundle.xlsx](https://github.com/charlymr/XlsxReaderWriter/files/2083990/FileShippedInBundle.xlsx)

**Comment by charlymr** [comment]
@kuglemic I will be looking into this sorry for the delay I have a lot in progress for the moment.
Can you confirm you are using Beta 3 please?

**Comment by kuglemic** [comment]
@charlymr No worries and thanks for your help. Yes, I'm using Beta 3. Just double checked it.

**Comment by charlymr** [comment]
@kuglemic Hi again. Sorry a bit short on time those day. I'll try and check at a later stage, maybe this week-end

**Comment by EricVoll** [comment]
@charlymr 
Hi!
We had the same problem and found the source of it.
**What we did:**
We had a not-empty Excel file and loaded it as a BRAOfficeDocumentPackage and saved it without changing anything. (I'll call the second file that went through the xlsxReaderWriter "edited file" and the original file "original file")
After comparing the two files (via renaming them to .zip files) we saw, that there where differences in four files, but only one had an impact on the success of opening it in Excel.
it was xl/workbook.xml
In the orignial file the <xr:revisionPtr> tag is above the <bookViews> tag. In the edited file it was the last  tag.
Changing its order solved the problem and made it readable by excel without a problem!

**I think we found the solution**
In the NSDictionary+OpenXmlString.m file we added a  "@"xr:revisionPtr" after the @"mc:AlternateContent" tag. After doing that it **worked perfectly**! (line 21)
We used the 2.4.0.beta.3 branch

The workbook tag then looked like this:
`@"workbook": @[
                                 @"xmlns", @"xmlns:r", @"fileVersion", @"fileSharing", @"workbookPr", @"workbookProtection", @"mc:AlternateContent",@"xr:revisionPtr", @"bookViews", @"sheets", @"functionGroups", @"externalReferences", @"definedNames", @"calcPr", @"oleSize", @"customWorkbookViews", @"pivotCaches", @"smartTagPr", @"smartTagTypes", @"webPublishing", @"fileRecoveryPr", @"webPublishObjects", @"extLst"
                                 ]`
We could commit our changes if you want us to?
We hope this helps others too!

Edit: "We" is me and @florrr

**Comment by charlymr** [comment]
Hello and thanks so much for the time you took pinning the issue. I am short on time lately and could not take more time searching! So a big thank you.

Please do create a pull request on the beta.3 branch and I will generate a beta.4 to confirm everything is working with everyone!

Thanks so much for contributing!

**Comment by EricVoll** [comment]
absolutely no problem!

We tried that. Allthough we are not too bad in programming, we do not know much about GitHub. So I think we made a mistake with the pull-Request?

**Comment by charlymr** [comment]
That's ok I will take your changes :) Thanks already for the great job

**Comment by charlymr** [comment]
This now fixed in beta 4
https://github.com/charlymr/XlsxReaderWriter/tree/2.4.0.Beta.4

Thanks @luchspeter and @Florrr

**Comment by anikaseibezeder** [comment]
Maybe anyone can help me with my files? (Same issue = the changed file cannot be opened by excel)

I've tried to look through the structure of the archive, but I don't really know how to change this in code, or if it is relevant...
The differences I've noticed:

- in xl/workbook.xml the order of the attributes in the <workbook> tag is different
- in xl/workbook.xml the order of the attributes in the <xr:revisionPtr> tag is different (coauthVersionLast and coauthVersionMax are switched)

I would really appreciate it, if someone could help me out!!!!!

[Files.zip](https://github.com/charlymr/XlsxReaderWriter/files/2821837/Files.zip)
