### ISSUE TITLE
Pods Import 

### ISSUE THREAD

**Issue by glockyb** [charlymr/XlsxReaderWriter#9]
Unable to find a specification for `SSZipArchive (~> 2.1)` depended upon by `XlsxReaderWriter`

**Comment by charlymr** [comment]
Please check to BETA 4. And point directly to the pod spec.
Thanks.

```ruby 
pod 'XlsxReaderWriter', '~> 2.4.0-beta', :source => 'https://github.com/charlymr/XlsxReaderWriter-Podspecs.git'
```

Denis

**Comment by charlymr** [comment]
A much faster fix is, just bare in mind it is pointing to a Beta branch so you may want to check on a regular basis. This branch is stable enough so I will probably release this one once I get feedback (or not) on it.

``` ruby
pod 'XlsxReaderWriter', podspec: 'https://raw.githubusercontent.com/charlymr/XlsxReaderWriter/2.4.0.Beta.4/XlsxReaderWriter.podspec'
```
